version: '3.8'

services:
  unreal-builder:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - .:/SequencePlugin
    command: ./SequencePlugin/buildPlugin.sh
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8000M
