name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login ghcr.io --username andygruening --password ${{ secrets.ACCESS_KEY }}
    - name: Build Unreal Project
      run: docker build . --file Dockerfile --tag sequence-unreal:$(date +%s)
