name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: macos-latest-large
    steps:
    - name: Check out Repository
      uses: actions/checkout@v4
    - name: Setup Docker
      run: |
        brew install colima
        brew install docker
        colima start
    - name: Docker Login
      env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      run: docker login ghcr.io --username andygruening --password $ACCESS_KEY
    - name: Pull UnrealEngine Image
      uses: actions/cache@v4
      run: docker pull ghcr.io/epicgames/unreal-engine:dev-slim-5.4.3
    - name: Build Unreal Project
      run: | 
        docker build . --file Dockerfile --tag sequence-unreal
        docker run sequence-unreal
